---
- name: Extract golang
  unarchive:
      src: "https://dl.google.com/go/go1.10.3.linux-armv6l.tar.gz"
      dest: /usr/local/
      remote_src: yes

- name: Append gopath to /etc/profile
  lineinfile:
    path: /etc/profile
    line: 'PATH="$PATH:/usr/local/go/bin"'
